# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Movie Management CI

on:
  push:
    branches: [ "master", "main", "hexagone" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 20.x, 18.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Debug repository structure
      run: |
        echo "All .spec.ts files in repository:"
        find . -name "*.spec.ts" | sort
        echo "Directory structure of src/modules:"
        ls -la src/modules || echo "modules directory not found"
        echo "Auth module structure (if exists):"
        ls -la src/modules/auth || echo "auth directory not found"
        echo "Test directory structure (if exists):"
        ls -la src/modules/auth/test || echo "test directory not found"
    - run: npm test

