# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Movie Management CI

on:
  push:
    branches: [ "master", "main", "hexagone", "movie", "ticket", "e2e", "bulk-movies" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 20.x, 18.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  e2e:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x, 20.x, 18.x, 16.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:e2e

    
# Uncomment the following job to enable automatic deployment to Heroku
# Note: You'll need to set up the HEROKU_API_KEY and HEROKU_APP_NAME secrets in your GitHub repository

# deploy:
#   needs: [test, e2e]
#   runs-on: ubuntu-latest
#   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
#   
#   steps:
#     - uses: actions/checkout@v4
#     
#     # Set up Node.js for potential build steps
#     - name: Use Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '18.x'
#         cache: 'npm'
#     
#     # Install dependencies
#     - run: npm ci
#     
#     # Build the application if needed
#     - run: npm run build
#     
#     # Deploy to Heroku
#     - name: Deploy to Heroku
#       uses: akhileshns/heroku-deploy@v3.12.14
#       with:
#         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#         heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#         heroku_email: ${{ secrets.HEROKU_EMAIL }}
#         procfile: "web: npm run start:prod"
#         
#     # Optional: Run database migrations if needed
#     # - name: Run database migrations
#     #   run: |
#     #     heroku run npm run migration:run --app ${{ secrets.HEROKU_APP_NAME }}
#     
#     # Optional: Add Health check after deployment
#     # - name: Health check
#     #   run: |
#     #     sleep 30
#     #     curl https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/health
